### ISSUE TITLE
Design ui for mood tracker

### ISSUE THREAD

**Issue by jyaneshseeam** [UPEI-Android/group-project-mindjogg#140]
## Context 
We need to design the UI for the mood tracker

## Problem 
We do not have the UI design for the mood tracker
## Solution 

- [ ] Find what information about the user needs to be stored 
- [ ] Design a UI entering for moods 
- [ ] Submit for peer review

**Comment by jyaneshseeam** [comment]
@sontushkpaul @DemiAdisa  @ja-chisholm 

Check out https://www.figma.com/file/3714aYKYor5Sll85z8yuqm/MindjoggUI?node-id=0%3A1
Let me know which one of the 2 designs for the mood tracker you like, what to add, any ideas, input would be appreciated.
