### ISSUE TITLE
Deliver UX testing Checklist to the potential end user 

### ISSUE THREAD

**Issue by sontushkpaul** [UPEI-Android/group-project-mindjogg#50]
## Context
The initial prototype of the MindJoGG app has been created using Figma app. 
## Problem 
We do not know about our initial prototype's user experience which is important to guide us to build the app. We need UX feedback from our potential end user (an post-secondary student preferably). 

## Solution 

- [x] Create UX questionnaire in google forms 
- [x] Ask end user to participate in the UX testing
- [x] Share the prototype link and the questionnaire link to the end users

**Comment by DemiAdisa** [comment]
Update: There are now 7 responses on the Google Form, Please check them out

**Comment by DemiAdisa** [comment]
Update: Survey is currently sitting at 9 responses

**Comment by DemiAdisa** [comment]
Issue will be closed now
